import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Menu } from "typings";
import styles from "@/styles/Home.module.css";
import Header from "components/Header";
import Sidebar from "components/Sidebar";
import MenuCard from "components/MenuCard";
import { useEffect, useState } from "react";
import { ShoppingCartProvider } from "context/ShoppingCartContext";
import { useShoppingCart } from "../../context/ShoppingCartContext";
import Checkout from "components/Checkout";

interface Props {
  Burger: Menu[];
  BBQs: Menu[];
  Breads: Menu[];
  Chocolates: Menu[];
  Drinks: Menu[];
}

export default function Home() {
  const BASE_URL = "https://free-food-menus-api-production.up.railway.app";

  const { cartQuantity, FoodData } = useShoppingCart();
  console.log("Here it this:",FoodData);

  return (
    //can be put only in the area that it is being useful => global storage house
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex flex-row space-x-28">
          <Sidebar />
          <MenuCard
            foodData = {FoodData}
          />
          {/* <Checkout Data={Data} />  */}
        </div>
      </main>
      </>
 );
}
