import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Menu } from "typings";
import styles from "@/styles/Home.module.css";
import Header from "components/Header";
import Sidebar from "components/Sidebar";
import MenuCard from "components/MenuCard";
import { useEffect, useState } from "react";
import { ShoppingCartProvider } from "context/ShoppingCartContext";
import { useShoppingCart } from '../../context/ShoppingCartContext';
import Checkout from "components/Checkout";

interface Props {
  Burger: Menu[];
  BBQs: Menu[];
  Breads: Menu[];
  Chocolates: Menu[];
  Drinks: Menu[];
}

export default function Home() {

  const [Data,setData] = useState<Menu[]>([]);
  const [Burger,setBurger] = useState<Menu[]>([]);
  const [BBQs,setBBQs] = useState<Menu[]>([]);
  const [Breads,setBread] = useState<Menu[]>([]);
  const [Chocolates, setChocolates] = useState<Menu[]>([]);
  const [Drinks, setDrinks] = useState<Menu[]>([]);

  const BASE_URL = 'https://free-food-menus-api-production.up.railway.app'

  const {cartQuantity} = useShoppingCart();

  useEffect(() => {
    fetch(`${BASE_URL}/burgers`).then((res) => res.json()).then((data)=>{
      Data.push(data);
      setBurger(data);
    })

    fetch(`${BASE_URL}/bbqs`).then((res) => res.json()).then((data)=>{
      Data.push(data);
      setBBQs(data);
    })

    fetch(`${BASE_URL}/breads`).then((res) => res.json()).then((data)=>{
      Data.push(data);
      setBread(data);
    })

    fetch(`${BASE_URL}/chocolates`).then((res) => res.json()).then((data)=>{
      Data.push(data);
      setChocolates(data);
    })

    fetch(`${BASE_URL}/drinks`).then((res) => res.json()).then((data)=>{
      Data.push(data);
      setDrinks(data);
    })

    setData(Data);

  },[])

  return (
    <ShoppingCartProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex flex-row space-x-28">
          <Sidebar />
          <MenuCard
            Burger={Burger}
            BBQs={BBQs}
            Breads={Breads}
            Chocolates={Chocolates}
            Drinks={Drinks}
          />
          <Checkout
            Data={Data}
          />
        </div>
      </main>
    </ShoppingCartProvider>
  );
}